# Generated by .github/workflows/build.yml on each release — do not edit by hand.
class Vbrain < Formula
  desc "Personal knowledge base — Claude Code skills + Go binary + SQLite FTS5"
  homepage "https://github.com/virtual360-io/vbrain"
  version "0.1.20"

  on_macos do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.20/vbrain-macos-apple-silicon"
      sha256 "93dc682b963a73e5c9fd6c6a348f52e887a02c5336413b726cd390e6e9b358c8"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.20/vbrain-macos-intel"
      sha256 "ef6e249a8bc0e91672ad049dfeebcb3ec33680abdeda10a85f89c57bc40e8206"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.20/vbrain-linux-arm64"
      sha256 "ebf96130e98e7957138ae86a9747a9c46f8083a607d76ec1b578f0ad942b95b8"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.20/vbrain-linux-intel"
      sha256 "dba96cd3157155aac7eaf1fec40a53528bf090b78af56738669e3ad9cc78b03e"
    end
  end

  def install
    bin.install Dir["vbrain-*"].first => "vbrain"
  end

  def caveats
    <<~CAVEATS
      Next, install the Claude Code skills and bootstrap your base (~/vbrain):
        vbrain install
    CAVEATS
  end

  test do
    assert_match "usage: vbrain", shell_output("#{bin}/vbrain 2>&1", 2)
  end
end
