# Generated by .github/workflows/build.yml on each release — do not edit by hand.
class Vbrain < Formula
  desc "Personal knowledge base — Claude Code skills + Go binary + SQLite FTS5"
  homepage "https://github.com/virtual360-io/vbrain"
  version "0.1.18"

  on_macos do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.18/vbrain-macos-apple-silicon"
      sha256 "f2f4a6a96c0515cf7cf08b480cc98cc6696939c6ec96a355040ba0b7c9343007"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.18/vbrain-macos-intel"
      sha256 "244b26e0ee71b8db1688c40254680a12bf1300ee305c4bbd6bc7af266eb25d52"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.18/vbrain-linux-arm64"
      sha256 "636f3ee7a1763a4f9f2f87ec290b8fcfc2143e8f48cf0359176835b0230a2daa"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.18/vbrain-linux-intel"
      sha256 "60ceb65488122e6806a92e8c9cebaaed4ed9ef65437f6065d387528067fee5b3"
    end
  end

  def install
    bin.install Dir["vbrain-*"].first => "vbrain"
  end

  def caveats
    <<~CAVEATS
      Next, install the Claude Code skills and bootstrap your base (~/vbrain):
        vbrain install
    CAVEATS
  end

  test do
    assert_match "usage: vbrain", shell_output("#{bin}/vbrain 2>&1", 2)
  end
end
