# Generated by .github/workflows/build.yml on each release — do not edit by hand.
class Vbrain < Formula
  desc "Personal knowledge base — Claude Code skills + Go binary + SQLite FTS5"
  homepage "https://github.com/virtual360-io/vbrain"
  version "0.1.11"

  on_macos do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.11/vbrain-macos-apple-silicon"
      sha256 "09df98eaad09bf644c9f8c860e633b9c971268553af1067529727462c1eb2486"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.11/vbrain-macos-intel"
      sha256 "6d4f2ba75a88aff031e8e60f046c3e13bc06525d3c5b6527bc71f2e56aa306c0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.11/vbrain-linux-arm64"
      sha256 "b2aa480fbca68ce601948ca77135ab723d4a803bae2d1f14e481390c981dea9b"
    end
    on_intel do
      url "https://github.com/virtual360-io/vbrain/releases/download/v0.1.11/vbrain-linux-intel"
      sha256 "d3f4e7158b4ae46dd6e907541b83211fed35172681493312812097df7a7d70cd"
    end
  end

  def install
    bin.install Dir["vbrain-*"].first => "vbrain"
  end

  def caveats
    <<~CAVEATS
      Next, install the Claude Code skills and bootstrap your base (~/vbrain):
        vbrain install
    CAVEATS
  end

  test do
    assert_match "usage: vbrain", shell_output("#{bin}/vbrain 2>&1", 2)
  end
end
